// Generated by Wrangler on Tue Jul 09 2024 23:09:36 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	MY_DB: D1Database;
	JAKARTA_DB: D1Database;
	BANDUNG_DB: D1Database;
}
